// Shared category config for the pet place finder tools.
// Phase A ships dog-parks only; fetch-places collects all four so Phase B
// (veterinarians, pet-stores, dog-daycare) needs no new Overpass run.
export const CATEGORIES = {
  'dog-parks': {
    ship: true,
    label: 'Dog Parks',
    singular: 'dog park',
    plural: 'dog parks',
    // OSM selector handled in fetch-places bucket(); listed here for reference
    osm: 'leisure=dog_park',
    minResults: 3,
    keepUnnamed: true,
    unnamedLabel: 'Dog park (unnamed on OpenStreetMap)',
    tagWhitelist: ['surface', 'barrier', 'fence_type', 'drinking_water', 'lit', 'dog', 'small_dog', 'access', 'website', 'opening_hours'],
    cityTitle: (name) => `Dog Parks in ${name}: Map + Park Weather`,
    cityH1: (name, pet) => `Dog parks in ${name}, scouted by ${pet}`,
    cityDesc: (n, name) => `All ${n} mapped dog parks in ${name} with addresses and distances, plus today's park verdict and the best park window from the WeatherPets team.`,
    landerTitle: `Dog Park Finder: Map + Today's Park Weather`,
    scoutBeat: (name) => `${name} Field Scout`,
  },
  'veterinarians': {
    ship: false,
    label: 'Veterinarians',
    singular: 'veterinarian',
    plural: 'veterinarians',
    osm: 'amenity=veterinary',
    minResults: 3,
    keepUnnamed: false,
    tagWhitelist: ['phone', 'website', 'opening_hours', 'emergency', 'healthcare:speciality'],
    cityTitle: (name) => `Veterinarians in ${name}: Map & Finder`,
    cityH1: (name, pet) => `Veterinarians in ${name}, mapped by ${pet}`,
    cityDesc: (n, name) => `${n} veterinary clinics in ${name} on one map with addresses and distances, plus trip-planning weather tips from the WeatherPets team.`,
    landerTitle: `Vet Near Me: Veterinarian Finder & Map`,
    scoutBeat: (name) => `${name} Health Desk`,
  },
  'pet-stores': {
    ship: false,
    label: 'Pet Stores',
    singular: 'pet store',
    plural: 'pet stores',
    osm: 'shop=pet',
    minResults: 3,
    keepUnnamed: false,
    tagWhitelist: ['phone', 'website', 'opening_hours', 'brand'],
    cityTitle: (name) => `Pet Stores in ${name}: Map & Local Finder`,
    cityH1: (name, pet) => `Pet stores in ${name}, mapped by ${pet}`,
    cityDesc: (n, name) => `${n} pet stores in ${name} on one map with addresses and distances, plus shopping-trip weather tips from the WeatherPets team.`,
    landerTitle: `Pet Store Finder: Shops Near You`,
    scoutBeat: (name) => `${name} Supply Desk`,
  },
  'dog-daycare': {
    ship: false,
    label: 'Dog Daycare & Boarding',
    singular: 'dog daycare',
    plural: 'dog daycare and boarding spots',
    osm: 'amenity=animal_boarding|animal_daycare',
    minResults: 3,
    keepUnnamed: false,
    tagWhitelist: ['phone', 'website', 'opening_hours', 'amenity'],
    cityTitle: (name) => `Dog Daycare & Boarding in ${name}: Map`,
    cityH1: (name, pet) => `Dog daycare in ${name}, mapped by ${pet}`,
    cityDesc: (n, name) => `${n} dog daycare and boarding options in ${name} on one map with addresses and distances, from the WeatherPets team.`,
    landerTitle: `Dog Daycare & Boarding Finder`,
    scoutBeat: (name) => `${name} Daycare Desk`,
  },
};
